apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: taskmaster-deployment
spec:
  selector:
    matchLabels:
      app: taskmaster
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: taskmaster
    spec:
      containers:
        - name: taskmaster
          image: adijaiswal/prodtaskmaster:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster

